
from app.github_client import github_get, github_post

OWNER = "pruthviraj-m"
REPO = "ci-cd-intelligence-agent"


def create_pull_request(
    branch,
    run_id,
    diagnosis,
    patch,
):
    existing_pr = find_existing_pr(branch)

    if existing_pr:
        print("Existing PR found. Reusing it.")
        return existing_pr
    url = (
        f"https://api.github.com/repos/"
        f"{OWNER}/{REPO}/pulls"
    )

    evidence_text = "\n".join(
        f"- [{item.source}] {item.observation}"
        for item in diagnosis.evidence
    )

    files_text = "\n".join(
        f"- {file}"
        for file in diagnosis.affected_files
    )

    body = f"""## 🤖 AI CI/CD Remediation

### CI Failure

**Workflow Run:** `{run_id}`

### Root Cause

{diagnosis.root_cause}

### Evidence

{evidence_text}

### Affected Files

{files_text}

### Proposed Fix

{diagnosis.suggested_fix}

### Validation

- Patch generated by AI
- Patch validated against current source
- Tests executed after patch
- **All tests passed**

### Risk

**{diagnosis.risk_level}**

### Confidence

**{diagnosis.confidence}**

---

This pull request was generated automatically by the CI/CD Intelligence Agent.
"""

    data = {
        "title": f"🤖 AI Fix: CI failure #{run_id}",
        "head": branch,
        "base": "main",
        "body": body,
    }

    return github_post(url, data)

def get_pull_request_reviews(pr_number):
    url = (
        f"https://api.github.com/repos/"
        f"{OWNER}/{REPO}/pulls/{pr_number}/reviews"
    )

    return github_get(url)

def is_pr_approved(pr_number):
    reviews = get_pull_request_reviews(pr_number)

    for review in reviews:
        if review["state"] == "APPROVED":
            return True

    return False

def find_existing_pr(branch):
    url = (
        f"https://api.github.com/repos/"
        f"{OWNER}/{REPO}/pulls"
    )

    data = github_get(
        url,
        params={
            "state": "open",
            "head": f"{OWNER}:{branch}",
            "base": "main",
        },
    )

    if not data:
        return None

    return data[0]