from app.github_client import github_post


OWNER = "pruthviraj-m"
REPO = "ci-cd-intelligence-agent"


def create_pull_request(
    branch,
    run_id,
    diagnosis,
    patch,
):
    url = (
        f"https://api.github.com/repos/"
        f"{OWNER}/{REPO}/pulls"
    )

    evidence_text = "\n".join(
        f"- [{item.source}] {item.observation}"
        for item in diagnosis.evidence
    )

    files_text = "\n".join(
        f"- {file}"
        for file in diagnosis.affected_files
    )

    body = f"""## 🤖 AI CI/CD Remediation

### CI Failure

**Workflow Run:** `{run_id}`

### Root Cause

{diagnosis.root_cause}

### Evidence

{evidence_text}

### Affected Files

{files_text}

### Proposed Fix

{diagnosis.suggested_fix}

### Validation

- Patch generated by AI
- Patch validated against current source
- Tests executed after patch
- **All tests passed**

### Risk

**{diagnosis.risk_level}**

### Confidence

**{diagnosis.confidence}**

---

This pull request was generated automatically by the CI/CD Intelligence Agent.
"""

    data = {
        "title": f"🤖 AI Fix: CI failure #{run_id}",
        "head": branch,
        "base": "main",
        "body": body,
    }

    return github_post(url, data)